### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by Batarian711** [jedmao/queso#7]
Hello. I want to design a logo for you. If you like it, I will give you a present. What do you think?

**Comment by jedmao** [comment]
That would be most excellent! I'm just at the beginning stages of this project and I have a newborn 👶 I'm taking care of, so I'm trying my best to find time to make more of it, but I've definitely been thinking I need some kind of dripping cheese logo at some point. What are your thoughts?

**Comment by Batarian711** [comment]
I designed a logo like this in accordance with your wishes. A cheese-like Q letter. What dou you think ? 
![q](https://user-images.githubusercontent.com/41051393/55282784-9e555580-535c-11e9-941f-b39425257ebe.jpg)

**Comment by jedmao** [comment]
Thanks for the attempt! That would be a very literal representation of queso. In Texas, when someone says queso it's always the dripping cheese variety. Basically, it has to have dripping cheese. Are you familiar with a bowl of queso? It's like a liquid cheese.

**Comment by Batarian711** [comment]
I tried to make a  cheese a minimalist logo. What dou you think? Is there anything you'd like to add ?

**Comment by jedmao** [comment]
Oh, I actually just added a logo to the Readme some minutes ago. I do like your dripping 🧀 wedge though. That's pretty nice! Let me give it some thought. Maybe a combination of some elements.

**Comment by Batarian711** [comment]
Let me know when you decide. See you 😊

**Comment by jedmao** [comment]
Do you have the vector version so I can use your cheese wedge?

**Comment by Batarian711** [comment]
I have the vector in my hand. Do you want my logo as vector?

**Comment by jedmao** [comment]
Yes, that would be ideal.

**Comment by jedmao** [comment]
Thanks! I drew the vector shapes to match your 🧀 and pushed a new logo. It looks like this:

# [![Queso](/jedmao/queso/raw/master/media/header.png)](https://github.com/jedmao/queso)

What do you think?

**Comment by Batarian711** [comment]
Please tell me the font type and I'll send you variations of this logo like png jpg for you

**Comment by jedmao** [comment]
I actually adjusted the font and reduced the nodes by about 80%. The vector file is [here](https://github.com/jedmao/queso/blob/master/media/queso-logo.cdr).

The only thing I need right now is a favicon. Do you think you could create a dripping cheese wedge favicon.ico file?

**Comment by jedmao** [comment]
To be clear, the favicon should have a transparent background, so it would be _just_ the cheese wedge and no background color or anything.

**Comment by Batarian711** [comment]
I don't quite understand you. You want me to make a new logo? Didn't you like the logo I designed for you ?

**Comment by jedmao** [comment]
No I don't want you to make a new logo. I like the cheese wedge you adjust already designed and I've already incorporated it into the logo. I'm just asking for a tiny favicon with just the cheese and no lettering.

**Comment by jedmao** [comment]
Do you know what a Favicon is?

**Comment by Batarian711** [comment]
Yeah, I know you just want a cheese favicon.

**Comment by Batarian711** [comment]
Is that what you're talking about?
![sss](https://user-images.githubusercontent.com/41051393/55371188-f4193180-5505-11e9-93ad-af11fa8848d5.jpg)

**Comment by jedmao** [comment]
Yep! But it should have a transparent background as a PNG @ 64x64px, trimmed to transparent pixels. Can you do that?

See https://en.wikipedia.org/wiki/Favicon#File_format_support

**Comment by Batarian711** [comment]
Tell me the font . I'il arrange them all and send you a PR.

**Comment by jedmao** [comment]
Hmm... sorry, but I really don't think you understand what I'm asking for, as no font is required for just a cheese wedge. Nevermind, I was able to create the Favicon myself. Thanks for the cheese wedge though! I definitely used it!
